name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "532a61acea547182dd75505fc5de8554cdda0cbf0933cfbb0c366b8757a93c21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
