name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3857d47d74be2378e393a819ebf7d7d5118f8ed79ff56617397abb325fdbec0f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
