name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "819b6a912855bb4421922cb314e61fdb595876eb65195c3e3f08516463fef514"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
