name = "New Progression"
author = "Ozoku"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62c5f87e3182ae8bd5e00bc29bba06afad64c0db281f54602e6e7dfd4c427d1d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
