name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5836de65f49d9d0d6c74c93e78441cb4ac7d6438b3bf87d0112d050d80469b8b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
