name = "New Progression"
author = "Ozoku"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7658d12bd1de3e686125bf2646ee226bff6d57b967a2457c0ebd876d8554bb83"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
