name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cc03fc3a7acde10753daf92aed41a9a59fc6ad69981e99adff23c711eaec9b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
