name = "New Progression"
author = "Ozoku"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c96bc457017cdcdb60e1655484f0510fba90ad6ef6b038905932274164f49092"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
