name = "New Progression"
author = "Ozoku"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "200972eb37507870258fc37e70af97eaa354e3fb0b11e42261e09653fad72e0e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.185"
